name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and push
        uses: ./.github/actions/main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  kind:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind-node: 
          - kindest/node:v1.15.3@sha256:27e388752544890482a86b90d8ac50fcfa63a2e8656a96ec5337b902ec8e5157
          - kindest/node:v1.14.6@sha256:464a43f5cf6ad442f100b0ca881a3acae37af069d5f96849c1d06ced2870888d
          - kindest/node:v1.13.10@sha256:2f5f882a6d0527a2284d29042f3a6a07402e1699d792d0d5a9b9a48ef155fa2a
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.1.0
        with:
          image: ${{ matrix.kind-node }}
      - name: Install pulumi
        run: |
          yarn
          yarn build
          yarn link
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:/home/runner/.pulumi/bin
      - name: Run integration tests
        working-directory: tests/integration
        run: |
          export KUBECONFIG="$(kind get kubeconfig-path)"
          export PATH=$PATH:/home/runner/.pulumi/bin
          export PULUMI_CONFIG_PASSPHRASE=hello
          yarn link @timmyers/pulumi-k8s-metrics-server
          yarn
          pulumi login --local
          pulumi stack init main
          pulumi up
          kubectl version
          kubectl get po -n kube-system
