name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and push
        uses: ./.github/actions/main
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  kind:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind-node: 
          - kindest/node:v1.16.3@sha256:bced4bc71380b59873ea3917afe9fb35b00e174d22f50c7cab9188eac2b0fb88
          - kindest/node:v1.15.6@sha256:1c8ceac6e6b48ea74cecae732e6ef108bc7864d8eca8d211d6efb58d6566c40a
          - kindest/node:v1.14.9@sha256:00fb7d424076ed07c157eedaa3dd36bc478384c6d7635c5755746f151359320f
          - kindest/node:v1.13.12@sha256:ad1dd06aca2b85601f882ba1df4fdc03d5a57b304652d0e81476580310ba6289
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.1.0
        with:
          version: v0.6.0
          image: ${{ matrix.kind-node }}
      - name: Install pulumi
        run: |
          yarn
          yarn build
          yarn global bin
          yarn global add yalc
          /home/runner/.yarn/bin/yalc publish
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:/home/runner/.pulumi/bin
      - name: Run integration tests
        working-directory: tests/integration
        run: |
          export KUBECONFIG="$(kind get kubeconfig-path)"
          export PATH=$PATH:/home/runner/.pulumi/bin
          export PULUMI_CONFIG_PASSPHRASE=hello
          /home/runner/.yarn/bin/yalc add @timmyers/pulumi-k8s-metrics-server
          yarn
          pulumi login --local
          pulumi stack init main
          pulumi up -y --skip-preview
          kubectl version
          kubectl get po -n kube-system
